name: Build and store PhotoAtom Frontend Docker Image

on:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - frontend/**
      - .github/workflows/build-docker-image.yml
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/build-docker-image.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  build_push_image:
    name: Building and storing PhotoAtom Frontend Docker Image
    uses: PhotoAtom/automations/.github/workflows/build-docker-image.yml@main
    with:
      dev_version_name: dev
      image_name: photoatom_frontend
      image_proper_name: PhotoAtom Frontend
      pre_build_script: |
        sed -i "s|0.0.1|$SEMVER_VERSION|g" package.json
      build_path: frontend
    secrets: inherit

